version: '3'

# anchor_build: &anchor_build
#   deps: []
#   sources:
#     - ./Taskfile.yml
#     - ./**/*
#   env:
#     SOME_VAR: 0
# vars:
#   build_tool_bin: './build_tool/build_tool{{- if eq OS "windows" }}.exe{{ end -}}'
# includes:
#   subproject:
#     taskfile: ./subproject/
#     dir: ./subproject/

tasks:
  build:
    sources:
      - '*.c'
      - Taskfile.yml
      - build.sh
      - meson.build
    generates:
      - ./build/piewin
    cmds:
      - rm -rf build
      - meson setup build
      - meson compile -C build
      - |
        # Put compile_commands.json at project root (above ./build).
        if [ -f build/compile_commands.json ]; then
          ln -sfn build/compile_commands.json compile_commands.json 2>/dev/null || cp build/compile_commands.json compile_commands.json
        else
          # Fallback for older Meson/Ninja: generate it via ninja's compdb tool.
          ninja -C build -t compdb > compile_commands.json
        fi






